const styles = {
  root: {
    display: "flex",
    height: "100vh",
    background: "#0a0f1e",
    color: "#e2e8f0",
    fontFamily: "'DM Sans', 'Noto Sans JP', sans-serif",
    overflow: "hidden",
  },
  sidebar: {
    width: 220,
    background: "#0d1526",
    borderRight: "1px solid #1e2d48",
    display: "flex",
    flexDirection: "column",
    padding: "24px 0",
    flexShrink: 0,
  },
  logo: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "0 20px 28px",
    borderBottom: "1px solid #1e2d48",
    marginBottom: 16,
  },
  logoIcon: { fontSize: 28, color: "#38bdf8" },
  logoTitle: { fontSize: 15, fontWeight: 800, letterSpacing: 3, color: "#f1f5f9" },
  logoSub: { fontSize: 9, color: "#38bdf8", letterSpacing: 2 },
  nav: { display: "flex", flexDirection: "column", gap: 2, padding: "0 12px" },
  navItem: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "10px 12px",
    borderRadius: 8,
    background: "none",
    border: "none",
    color: "#64748b",
    fontSize: 13,
    cursor: "pointer",
    textAlign: "left",
    position: "relative",
    transition: "all 0.15s",
  },
  navItemActive: {
    background: "#172040",
    color: "#38bdf8",
    fontWeight: 600,
  },
  navIcon: { fontSize: 15, width: 20, textAlign: "center" },
  navDot: {
    position: "absolute",
    right: 10,
    width: 6,
    height: 6,
    borderRadius: "50%",
    background: "#38bdf8",
  },
  sidebarFooter: { marginTop: "auto", padding: "20px 20px 0" },
  footerStatus: { display: "flex", alignItems: "center", gap: 8 },
  statusDot: {
    width: 8, height: 8, borderRadius: "50%",
    background: "#34d399",
    boxShadow: "0 0 8px #34d399",
  },
  main: { flex: 1, display: "flex", flexDirection: "column", overflow: "hidden" },
  header: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "20px 32px",
    borderBottom: "1px solid #1e2d48",
    background: "#0d1526",
    flexShrink: 0,
  },
  headerLeft: {},
  headerRight: {},
  pageTitle: { margin: 0, fontSize: 20, fontWeight: 700, color: "#f1f5f9" },
  pagePath: { fontSize: 11, color: "#475569", marginTop: 2, display: "block" },
  dateBadge: {
    fontSize: 12,
    color: "#38bdf8",
    background: "#172040",
    border: "1px solid #1e3a5f",
    padding: "5px 12px",
    borderRadius: 6,
    fontWeight: 600,
    letterSpacing: 1,
  },
  content: { flex: 1, overflow: "auto", padding: 28 },

  grid2: {
    display: "grid",
    gridTemplateColumns: "repeat(4, 1fr)",
    gap: 16,
  },
  card: {
    background: "#111827",
    border: "1px solid #1e2d48",
    borderRadius: 12,
    padding: 20,
  },
  cardHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 16,
  },
  cardTitle: { fontSize: 14, fontWeight: 700, color: "#94a3b8", letterSpacing: 0.5 },
  statCard: {
    display: "flex",
    alignItems: "center",
    gap: 16,
  },
  statIcon: {
    width: 48,
    height: 48,
    borderRadius: 12,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 20,
    flexShrink: 0,
  },
  statBody: {},
  statLabel: { fontSize: 11, color: "#64748b", marginBottom: 4 },
  statValue: { display: "flex", alignItems: "baseline", gap: 4 },
  statNum: { fontSize: 28, fontWeight: 800 },
  statUnit: { fontSize: 13, color: "#64748b" },

  table: { width: "100%", borderCollapse: "collapse" },
  th: {
    textAlign: "left",
    fontSize: 11,
    color: "#475569",
    fontWeight: 600,
    padding: "8px 12px",
    borderBottom: "1px solid #1e2d48",
    letterSpacing: 0.5,
  },
  tr: { borderBottom: "1px solid #0f172a", transition: "background 0.1s" },
  td: { padding: "10px 12px", fontSize: 13 },
  mono: { fontFamily: "monospace", fontSize: 12, color: "#64748b" },

  statusBadge: {
    fontSize: 11,
    padding: "3px 8px",
    borderRadius: 4,
    fontWeight: 600,
  },
  statusOk: { background: "#064e3b", color: "#6ee7b7" },
  statusErr: { background: "#450a0a", color: "#fca5a5" },

  pageActions: { display: "flex", justifyContent: "flex-end", marginBottom: 16 },
  btnPrimary: {
    background: "linear-gradient(135deg, #0ea5e9, #6366f1)",
    color: "#fff",
    border: "none",
    padding: "9px 18px",
    borderRadius: 8,
    fontSize: 13,
    fontWeight: 600,
    cursor: "pointer",
  },
  btnDanger: {
    background: "#450a0a",
    color: "#fca5a5",
    border: "1px solid #7f1d1d",
    padding: "6px 12px",
    borderRadius: 6,
    fontSize: 12,
    cursor: "pointer",
    flexShrink: 0,
  },
  btnDangerSm: {
    background: "#450a0a",
    color: "#fca5a5",
    border: "1px solid #7f1d1d",
    padding: "4px 10px",
    borderRadius: 5,
    fontSize: 11,
    cursor: "pointer",
  },

  formCard: {
    background: "#111827",
    border: "1px solid #1e3a5f",
    borderRadius: 12,
    padding: 20,
    marginBottom: 20,
  },
  formGrid: { display: "grid", gridTemplateColumns: "repeat(3, 1fr)", gap: 12, margin: "16px 0" },
  formField: { display: "flex", flexDirection: "column", gap: 6 },
  label: { fontSize: 11, color: "#64748b", fontWeight: 600 },
  input: {
    background: "#0d1526",
    border: "1px solid #1e2d48",
    borderRadius: 6,
    padding: "8px 12px",
    color: "#e2e8f0",
    fontSize: 13,
    outline: "none",
  },

  cardGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(300px, 1fr))", gap: 12 },
  adCard: {
    background: "#111827",
    border: "1px solid #1e2d48",
    borderRadius: 12,
    padding: 16,
    display: "flex",
    alignItems: "center",
    gap: 14,
  },
  adThumb: {
    width: 52,
    height: 52,
    background: "#172040",
    borderRadius: 10,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 24,
    flexShrink: 0,
  },
  adInfo: { flex: 1, minWidth: 0 },
  adTitle: { fontSize: 14, fontWeight: 600, color: "#e2e8f0", marginBottom: 4 },
  adMeta: { fontSize: 11, color: "#64748b", marginBottom: 4 },
  badge: {
    background: "#172040",
    border: "1px solid #1e3a5f",
    color: "#94a3b8",
    fontSize: 11,
    padding: "2px 8px",
    borderRadius: 4,
  },

  storeName: { fontWeight: 600, color: "#e2e8f0" },

  deliveryLayout: { display: "flex", gap: 16, alignItems: "flex-start" },
  adSelectItem: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    width: "100%",
    padding: "10px 12px",
    background: "none",
    border: "1px solid transparent",
    borderRadius: 8,
    cursor: "pointer",
    textAlign: "left",
    marginBottom: 4,
  },
  adSelectItemActive: {
    background: "#172040",
    border: "1px solid #1e3a5f",
  },
  adSelectThumb: { fontSize: 20 },
  storeGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(140px, 1fr))", gap: 10 },
  storeToggle: {
    background: "#0d1526",
    border: "1px solid #1e2d48",
    borderRadius: 10,
    padding: "16px 12px",
    cursor: "pointer",
    color: "#94a3b8",
    textAlign: "center",
    position: "relative",
    transition: "all 0.15s",
  },
  storeToggleActive: {
    background: "#0c2a1f",
    border: "1px solid #065f46",
    color: "#6ee7b7",
  },
  activeCheck: {
    position: "absolute",
    top: 8,
    right: 10,
    width: 18,
    height: 18,
    background: "#34d399",
    borderRadius: "50%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 10,
    color: "#022c22",
    fontWeight: 800,
  },

  filterBar: {
    display: "flex",
    alignItems: "center",
    gap: 16,
    marginBottom: 14,
    background: "#111827",
    border: "1px solid #1e2d48",
    borderRadius: 10,
    padding: "10px 16px",
  },
  select: {
    background: "#0d1526",
    border: "1px solid #1e2d48",
    borderRadius: 6,
    padding: "5px 10px",
    color: "#e2e8f0",
    fontSize: 12,
    outline: "none",
    cursor: "pointer",
  },

  toast: {
    position: "fixed",
    bottom: 28,
    right: 28,
    background: "#064e3b",
    border: "1px solid #065f46",
    color: "#6ee7b7",
    padding: "12px 20px",
    borderRadius: 10,
    fontSize: 13,
    fontWeight: 600,
    zIndex: 9999,
    display: "flex",
    alignItems: "center",
    gap: 8,
    boxShadow: "0 8px 24px #0005",
  },
  toastError: {
    background: "#450a0a",
    border: "1px solid #7f1d1d",
    color: "#fca5a5",
  },
  playerScreen: {
  width: "100%",
  height: "calc(100vh - 120px)",
  background: "#000",
  borderRadius: 12,
  overflow: "hidden",
  position: "relative",
  display: "flex",
  alignItems: "center",
  justifyContent: "center",
},

playerMedia: {
  width: "100%",
  height: "100%",
  objectFit: "contain",
  background: "#000",
},

playerInfo: {
  position: "absolute",
  bottom: 20,
  left: 20,
  background: "rgba(0,0,0,0.6)",
  color: "#fff",
  padding: "10px 14px",
  borderRadius: 8,
  fontSize: 14,
},

playerEmpty: {
  background: "#111827",
  border: "1px solid #1e2d48",
  borderRadius: 12,
  padding: 40,
  textAlign: "center",
  color: "#94a3b8",
},
};
export default styles;